services:
  galago-web-dev:
    build:
      context: .
      dockerfile: controller/Dockerfile.dev
    container_name: galago-web-dev
    ports:
      - "3010:3010"
      - "9229:9229" # Node.js debug port
    volumes:
      - ./controller:/app:cached
      - /app/node_modules # Persist node_modules
    environment:
      - NODE_ENV=development
      - PORT=3010
      - GRPC_SERVER_IP=host.docker.internal
      - GRPC_HOST=host.docker.internal
    stdin_open: true # for debugging
    tty: true # for debugging
    #network_mode: "host"
    networks:
      - app-network

volumes:
  sqlite_data:
  node_modules:
  npm_cache:

networks:
  app-network:
    driver: bridge
