#Production docker-compose file
services:
  galago-web:
    image: ghcr.io/sciencecorp/galago-web:latest
    # build:
    #   context: .
    #   dockerfile: controller/Dockerfile
    container_name: galago-web
    ports:
      - "3010:3010"
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3010
      - GRPC_SERVER_IP=localhost
    networks:
      - app-network

volumes:
  sqlite_data:

networks:
  app-network:
    driver: bridge
