name: main

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Add GitHub to known hosts
        run: |
          mkdir "$HOME/.ssh"
          ssh-keyscan github.com >> "$HOME/.ssh/known_hosts"
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.CI_PRIVATE_SSH_KEY }}
      - name: Setup dependencies
        uses: ./.github/actions/setup
      - name: Build protobufs
        run: ./bin/make proto
        shell: bash
      - name: Run tests
        run: ./bin/make test
        shell: bash
      - name: Run pytest tests
        run: ./bin/make pytest
      - name: Run unit tests
        run: ./bin/make unittest_py
        shell: bash
  