name: Publish Docker Images
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write  # Required for keyless signing
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push galago-web
        uses: docker/build-push-action@v4
        with:
          context: .
          file: controller/Dockerfile
          push: true
          tags: ghcr.io/sciencecorp/galago-web:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/sciencecorp/galago-web:buildcache
          cache-to: type=registry,ref=ghcr.io/sciencecorp/galago-web:buildcache,mode=max
      
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.4.0
      
      - name: Sign galago-web image
        run: cosign sign --yes ghcr.io/sciencecorp/galago-web:latest
        env:
          COSIGN_EXPERIMENTAL: 1
      
      - name: Build and push galago-db
        uses: docker/build-push-action@v4
        with:
          context: ./db
          file: db/Dockerfile
          push: true
          tags: ghcr.io/sciencecorp/galago-db:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/sciencecorp/galago-db:buildcache
          cache-to: type=registry,ref=ghcr.io/sciencecorp/galago-db:buildcache,mode=max
      
      - name: Sign galago-db image
        run: cosign sign --yes ghcr.io/sciencecorp/galago-db:latest
        env:
          COSIGN_EXPERIMENTAL: 1